### ISSUE TITLE
Not a work...

### ISSUE THREAD

**Issue by ffdown** [LarryJane491/Lora-Training-in-Comfy#3]
load StableDiffusion checkpoint: E:\AI\StableDiff\models/Stable-diffusion\photon_v1.safetensors
UNet2DConditionModel: 64, 8, 768, False, False
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
loading text encoder: <All keys matched successfully>
Enable xformers for U-Net
Traceback (most recent call last):
  File "E:\AI\ComfyUI\custom_nodes\LoRA-Training-in-Comfy\sd-scripts\train_network.py", line 1012, in <module>
    trainer.train(args)
  File "E:\AI\ComfyUI\custom_nodes\LoRA-Training-in-Comfy\sd-scripts\train_network.py", line 236, in train
    vae.set_use_memory_efficient_attention_xformers(args.xformers)
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\diffusers\models\modeling_utils.py", line 251, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\diffusers\models\modeling_utils.py", line 247, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\diffusers\models\modeling_utils.py", line 247, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\diffusers\models\modeling_utils.py", line 247, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\diffusers\models\modeling_utils.py", line 244, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\diffusers\models\attention_processor.py", line 216, in set_use_memory_efficient_attention_xformers
    raise e
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\diffusers\models\attention_processor.py", line 210, in set_use_memory_efficient_attention_xformers
    _ = xformers.ops.memory_efficient_attention(
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\xformers\ops\fmha\__init__.py", line 223, in memory_efficient_attention
    return _memory_efficient_attention(
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\xformers\ops\fmha\__init__.py", line 321, in _memory_efficient_attention
    return _memory_efficient_attention_forward(
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\xformers\ops\fmha\__init__.py", line 337, in _memory_efficient_attention_forward
    op = _dispatch_fw(inp, False)
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\xformers\ops\fmha\dispatch.py", line 120, in _dispatch_fw
    return _run_priority_list(
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\xformers\ops\fmha\dispatch.py", line 63, in _run_priority_list
    raise NotImplementedError(msg)
NotImplementedError: No operator found for `memory_efficient_attention_forward` with inputs:
     query       : shape=(1, 2, 1, 40) (torch.float32)
     key         : shape=(1, 2, 1, 40) (torch.float32)
     value       : shape=(1, 2, 1, 40) (torch.float32)
     attn_bias   : <class 'NoneType'>
     p           : 0.0
`decoderF` is not supported because:
    xFormers wasn't build with CUDA support
    attn_bias type is <class 'NoneType'>
    operator wasn't built - see `python -m xformers.info` for more info
`flshattF@0.0.0` is not supported because:
    xFormers wasn't build with CUDA support
    dtype=torch.float32 (supported: {torch.float16, torch.bfloat16})
    operator wasn't built - see `python -m xformers.info` for more info
`tritonflashattF` is not supported because:
    xFormers wasn't build with CUDA support
    dtype=torch.float32 (supported: {torch.float16, torch.bfloat16})
    operator wasn't built - see `python -m xformers.info` for more info
    triton is not available
`cutlassF` is not supported because:
    xFormers wasn't build with CUDA support
    operator wasn't built - see `python -m xformers.info` for more info
`smallkF` is not supported because:
    max(query.shape[-1] != value.shape[-1]) > 32
    xFormers wasn't build with CUDA support
    operator wasn't built - see `python -m xformers.info` for more info
    unsupported embed per head: 40
Traceback (most recent call last):
  File "E:\Anaconda3\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\Anaconda3\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\Anaconda3\lib\site-packages\accelerate\commands\launch.py", line 996, in <module>
    main()
  File "E:\Anaconda3\lib\site-packages\accelerate\commands\launch.py", line 992, in main
    launch_command(args)
  File "E:\Anaconda3\lib\site-packages\accelerate\commands\launch.py", line 986, in launch_command
    simple_launcher(args)
  File "E:\Anaconda3\lib\site-packages\accelerate\commands\launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['E:\\Anaconda3\\python.exe', 'custom_nodes/LoRA-Training-in-Comfy/sd-scripts/train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=E:\\AI\\StableDiff\\models/Stable-diffusion\\photon_v1.safetensors', '--train_data_dir=E:/AI/sonya/', '--output_dir=models/loras', '--logging_dir=./logs', '--log_prefix=TypeUSSR', '--resolution=512,512', '--network_module=networks.lora', '--max_train_epochs=40', '--learning_rate=1e-4', '--unet_lr=1e-4', '--text_encoder_lr=1e-5', '--lr_scheduler=cosine_with_restarts', '--lr_warmup_steps=0', '--lr_scheduler_num_cycles=1', '--network_dim=32', '--network_alpha=32', '--output_name=TypeUSSR', '--train_batch_size=1', '--save_every_n_epochs=10', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=4', '--cache_latents', '--prior_loss_weight=1', '--max_token_length=225', '--caption_extension=.txt', '--save_model_as=safetensors', '--min_bucket_reso=256', '--max_bucket_reso=1584', '--keep_tokens=0', '--xformers', '--shuffle_caption', '--clip_skip=2', '--optimizer_type=AdamW8bit', '--persistent_data_loader_workers', '--log_with=tensorboard']' returned non-zero exit status 1.
Train finished

**Comment by LarryJane491** [comment]
Have you installed the requirements?
I see a lot of "wasn't build with CUDA support". It suggests you don't have CUDA enabled.

Do you own a NVidia GPU? If you do, go there:
https://pytorch.org/
Choose the right options in the tabs (scroll down a little). For RTX cards you must choose 12.1.
It gives you a line of code. Use that line of code in your environment.

If you get the same error, reinstall the requirements for the node. Xformers is in these requirements, but maybe it is required to have CUDA installed before it.


If you don't have NVidia, this node won't work for now, sorry ^^'.

**Comment by ffdown** [comment]
Nvidia 4090, but i have 11.8 cuda...

**Comment by LarryJane491** [comment]
You should probably install CUDA 12.1 then ^^.
