### ISSUE TITLE
Training Ends Abruptly

### ISSUE THREAD

**Issue by apeluso17** [LarryJane491/Lora-Training-in-Comfy#35]
When I Queue Prompt to start training I receive this message:

    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\pelus\\AppData\\Local\\Programs\\Python\\Python310\\python.exe', 'C:/ComfyUI_windows_portable/ComfyUI/custom_nodes/Lora-Training-in-Comfy/sd-scripts/train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=C:\\ComfyUI_windows_portable\\ComfyUI\\models\\checkpoints\\dreamshaper_8.safetensors', '--train_data_dir=C:/Users/pelus/OneDrive/Documents/Videos/LoRA_Training/Test/database', '--output_dir=models/loras', '--logging_dir=./logs', '--log_prefix=PelusoDream', '--resolution=512,512', '--network_module=networks.lora', '--max_train_epochs=1', '--learning_rate=1e-4', '--unet_lr=1e-4', '--text_encoder_lr=1e-5', '--lr_scheduler=cosine_with_restarts', '--lr_warmup_steps=0', '--lr_scheduler_num_cycles=1', '--network_dim=32', '--network_alpha=32', '--output_name=PelusoDream', '--train_batch_size=1', '--save_every_n_epochs=10', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=8', '--cache_latents', '--prior_loss_weight=1', '--max_token_length=225', '--caption_extension=.txt', '--save_model_as=safetensors', '--min_bucket_reso=256', '--max_bucket_reso=1584', '--keep_tokens=0', '--xformers', '--shuffle_caption', '--clip_skip=2', '--optimizer_type=AdamW8bit', '--persistent_data_loader_workers', '--log_with=tensorboard']' returned non-zero exit status 1.
Train finished
Prompt executed in 4.47 seconds

**Comment by apeluso17** [comment]
Here is the entire CMD window:

C:\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
** ComfyUI startup time: 2024-04-02 21:19:24.812145
** Platform: Windows
** Python version: 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
** Python executable: C:\ComfyUI_windows_portable\python_embeded\python.exe
** Log path: C:\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   0.3 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager-main

Total VRAM 4096 MB, total RAM 16130 MB
Trying to enable lowvram mode because your GPU seems to have 4GB or less. If you don't want this use: --normalvram
Set vram state to: LOW_VRAM
Device: cuda:0 NVIDIA GeForce GTX 1650 Ti : cudaMallocAsync
VAE dtype: torch.float32
Using pytorch cross attention
### Loading: ComfyUI-Manager (V2.13.1)
### ComfyUI Revision: 2045 [b7b55931] | Released on '2024-03-04'

Import times for custom nodes:
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Lora-Training-in-Comfy
   0.4 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager-main


WARNING: this card most likely does not support cuda-malloc, if you get "CUDA error" please run ComfyUI with: --disable-cuda-malloc

Starting server

To see the GUI go to: http://127.0.0.1:8188
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
FETCH DATA from: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager-main\extension-node-map.json
got prompt
[]
C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Lora-Training-in-Comfy/sd-scripts/train_network.py
The following values were not passed to `accelerate launch` and had defaults used instead:
        `--num_processes` was set to a value of `1`
        `--num_machines` was set to a value of `1`
        `--mixed_precision` was set to a value of `'no'`
        `--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Lora-Training-in-Comfy\sd-scripts\train_network.py", line 11, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
Traceback (most recent call last):
  File "C:\Users\pelus\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\pelus\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\pelus\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\launch.py", line 1067, in <module>
    main()
  File "C:\Users\pelus\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\launch.py", line 1063, in main
    launch_command(args)
  File "C:\Users\pelus\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\launch.py", line 1057, in launch_command
    simple_launcher(args)
  File "C:\Users\pelus\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\launch.py", line 673, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\pelus\\AppData\\Local\\Programs\\Python\\Python310\\python.exe', 'C:/ComfyUI_windows_portable/ComfyUI/custom_nodes/Lora-Training-in-Comfy/sd-scripts/train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=C:\\ComfyUI_windows_portable\\ComfyUI\\models\\checkpoints\\dreamshaper_8.safetensors', '--train_data_dir=C:/Users/pelus/OneDrive/Documents/Videos/LoRA_Training/Test/database', '--output_dir=models/loras', '--logging_dir=./logs', '--log_prefix=PelusoDream', '--resolution=512,512', '--network_module=networks.lora', '--max_train_epochs=1', '--learning_rate=1e-4', '--unet_lr=1e-4', '--text_encoder_lr=1e-5', '--lr_scheduler=cosine_with_restarts', '--lr_warmup_steps=0', '--lr_scheduler_num_cycles=1', '--network_dim=32', '--network_alpha=32', '--output_name=PelusoDream', '--train_batch_size=1', '--save_every_n_epochs=10', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=21', '--cache_latents', '--prior_loss_weight=1', '--max_token_length=225', '--caption_extension=.txt', '--save_model_as=safetensors', '--min_bucket_reso=256', '--max_bucket_reso=1584', '--keep_tokens=0', '--xformers', '--shuffle_caption', '--clip_skip=2', '--optimizer_type=AdamW8bit', '--persistent_data_loader_workers', '--log_with=tensorboard']' returned non-zero exit status 1.
Train finished
Prompt executed in 4.83 seconds

**Comment by YunoGasaiAnime** [comment]
I have the same problem, i hope someone will resolve it

**Comment by apeluso17** [comment]
Hopefully we can get an answer soon!

**Comment by readycade** [comment]
*holds breath*

**Comment by chase2598** [comment]
the current problem is with the requirments_win.txt its outdated which means it dosent install all the moduals we need correctly so until that gets updated we are out of luck

**Comment by readycade** [comment]
or try kohya_ss while we're waiting

**Comment by apeluso17** [comment]
Thanks @chase2598 and @readycade 
For now I'm using an Instant LoRA. Here is a link to I video I made explaining it.
https://youtu.be/5Ca3jhL5Xus

**Comment by chase2598** [comment]
I actually found a fix if you go back to python 3.10.11 instead of 3.12.2 it will work

**Comment by apeluso17** [comment]
I was using python 3.10.10 and it didn't work for me???

**Comment by chase2598** [comment]
Then try using python 3.10.11 and make sure you have everything properly installed and then do pip install -r then the text document

**Comment by apeluso17** [comment]
I’m done with this plug-in. I wasted too much time.  :)

**Comment by readycade** [comment]
> Thanks @chase2598 and @readycade For now I'm using an Instant LoRA. Here is a link to I video I made explaining it. https://youtu.be/5Ca3jhL5Xus

yes, i'm using that as well, but the results aren't what i want. i need a trained lora with my own images.

**Comment by readycade** [comment]
the installing of older python versions was tried as well.. so obviously the requirements_win.txt is not correct

**Comment by chase2598** [comment]
Well not sure then cause when I installed 3.10.11 it worked

**Comment by readycade** [comment]
> Well not sure then cause when I installed 3.10.11 it worked

let's try AGAIN then

**Comment by readycade** [comment]
if you have python install via windows app store.. that will MESS UP EVERYTHING!!!! (SOLVED)

**Comment by chase2598** [comment]
Oh yah a windows app store in stall is never a good idea since it puts all the directories in a different location so it screws everything up

**Comment by readycade** [comment]
yes, it keeps using 3.12 packages or whatever the app store version is...
seeing 3.12 scroll down the terminal when i just installed 3.10 HMMMMMMMMM... SOMETHING WRONG HERE...
anyways, looks like it's gonna work now... (spoke too soon) prompt executed in 11.92 seconds.. (rolls eyes)

**Comment by apeluso17** [comment]
Yeah. I need to teach this to 25 students. No way in hell I'm going to try that. For now it's on the back burner. I'll try again when it's working with ease.

**Comment by readycade** [comment]
<img width="672" alt="LORA_MODELS_WORKING" src="https://github.com/LarryJane491/Lora-Training-in-Comfy/assets/122501283/0c6e0eca-68e6-4b6b-a9cb-e8a2ff0ba779">

so i finally got it to work...
you need to use this:

pip install torch==2.2.2+cu121 torchvision==0.17.2+cu121 torchaudio==2.2.2 -f https://download.pytorch.org/whl/cu121/torch_stable.html

and use SD 1.5 : v1-5-pruned.ckpt

also python needs to be version 3.10.11.

(what a mission.. but thank you author)

**Comment by apeluso17** [comment]
Congrats! That's the only Checkpoint you can use (SD 1.5 : v1-5-pruned.ckpt)??

**Comment by readycade** [comment]
> Congrats! That's the only Checkpoint you can use (SD 1.5 : v1-5-pruned.ckpt)??

that's the only one that's working so far... i tried SDXL first.. it says "trained" but in like 15 seconds... 
but when you load up 1.5 pruned, it says KEYS MATCH, so i got excited.. so as long as it says KEYS MATCH at the beginning it should work..

100% have a separate comfui for this purpose only. don't mess with your normal comfy.

**Comment by apeluso17** [comment]
Nice! Good Discovery! I guess in theory if you're training a LoRA it doesn't matter what the Checkpoint is??

**Comment by readycade** [comment]
> Nice! Good Discovery! I guess in theory if you're training a LoRA it doesn't matter what the Checkpoint is??

i was reading through his python script, it seems to want some sort of Dream checkpoint, if it doesn't find it, it defaults to something else.

**Comment by apeluso17** [comment]
Well hopefully this thread helps some people out!

**Comment by YunoGasaiAnime** [comment]
I still have this problem, and i followed the instructions

```
[Dataset 0]
loading image sizes.
100%|██████████████████████████████████████████████████████████████████████████████████| 25/25 [00:00<00:00, 44.75it/s]
make buckets
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (320, 704), count: 5
bucket 1: resolution (384, 640), count: 60
bucket 2: resolution (448, 576), count: 55
bucket 3: resolution (512, 512), count: 5
mean ar error (without repeats): 0.05953834748584825
preparing accelerator
loading model for process 0/1
load StableDiffusion checkpoint: D:\aaa\ComfyUI_windows_portable\ComfyUI\models\checkpoints\v1-5-pruned.ckpt
UNet2DConditionModel: 64, 8, 768, False, False
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
loading text encoder: <All keys matched successfully>
Enable xformers for U-Net
import network module: networks.lora
[Dataset 0]
caching latents.
checking cache validity...
100%|██████████████████████████████████████████████████████████████████████████████████████████| 25/25 [00:00<?, ?it/s]
caching latents...
 52%|██████████████████████████████████████████▋                                       | 13/25 [00:31<00:29,  2.44s/it]
Traceback (most recent call last):
  File "D:\aaa\ComfyUI_windows_portable\ComfyUI\custom_nodes\Lora-Training-in-Comfy-main\sd-scripts\train_network.py", line 1012, in <module>
    trainer.train(args)
  File "D:\aaa\ComfyUI_windows_portable\ComfyUI\custom_nodes\Lora-Training-in-Comfy-main\sd-scripts\train_network.py", line 266, in train
    train_dataset_group.cache_latents(vae, args.vae_batch_size, args.cache_latents_to_disk, accelerator.is_main_process)
  File "D:\aaa\ComfyUI_windows_portable\ComfyUI\custom_nodes\Lora-Training-in-Comfy-main\sd-scripts\library\train_util.py", line 1895, in cache_latents
    dataset.cache_latents(vae, vae_batch_size, cache_to_disk, is_main_process)
  File "D:\aaa\ComfyUI_windows_portable\ComfyUI\custom_nodes\Lora-Training-in-Comfy-main\sd-scripts\library\train_util.py", line 930, in cache_latents
    cache_batch_latents(vae, cache_to_disk, batch, subset.flip_aug, subset.random_crop)
  File "D:\aaa\ComfyUI_windows_portable\ComfyUI\custom_nodes\Lora-Training-in-Comfy-main\sd-scripts\library\train_util.py", line 2238, in cache_batch_latents
    raise RuntimeError(f"NaN detected in latents: {info.absolute_path}")
RuntimeError: NaN detected in latents: D:\Database\5_ske\101881329_p0.png
Traceback (most recent call last):
  File "C:\Users\fabiu\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\fabiu\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\fabiu\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\launch.py", line 996, in <module>
    main()
  File "C:\Users\fabiu\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\launch.py", line 992, in main
    launch_command(args)
  File "C:\Users\fabiu\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\launch.py", line 986, in launch_command
    simple_launcher(args)
  File "C:\Users\fabiu\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\fabiu\\AppData\\Local\\Programs\\Python\\Python310\\python.exe', 'D:/aaa/ComfyUI_windows_portable/ComfyUI/custom_nodes/Lora-Training-in-Comfy-main/sd-scripts/train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=D:\\aaa\\ComfyUI_windows_portable\\ComfyUI\\models\\checkpoints\\v1-5-pruned.ckpt', '--train_data_dir=D:/Database', '--output_dir=models/loras', '--logging_dir=./logs', '--log_prefix=ske', '--resolution=512,512', '--network_module=networks.lora', '--max_train_epochs=50', '--learning_rate=1e-4', '--unet_lr=1e-4', '--text_encoder_lr=1e-5', '--lr_scheduler=cosine_with_restarts', '--lr_warmup_steps=0', '--lr_scheduler_num_cycles=1', '--network_dim=32', '--network_alpha=32', '--output_name=ske', '--train_batch_size=1', '--save_every_n_epochs=10', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=27', '--cache_latents', '--prior_loss_weight=1', '--max_token_length=225', '--caption_extension=.txt', '--save_model_as=safetensors', '--min_bucket_reso=256', '--max_bucket_reso=1584', '--keep_tokens=0', '--xformers', '--shuffle_caption', '--clip_skip=2', '--optimizer_type=AdamW8bit', '--persistent_data_loader_workers', '--log_with=tensorboard']' returned non-zero exit status 1.
Train finished
```

**Comment by readycade** [comment]
https://civitai.com/articles/3093/how-to-resolve-dwposeonnxruntime-warning-or-how-to-run-multiple-pytorch-versions-side-by-side

**Comment by Battleshack** [comment]
Same problem here using the portable version with Python 3.11 and cu121.  The simple node works fine when prioritizing user site-packages in environment variables, but the advanced node returns this error. 
```
`raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['Z:\\Programmer\\ComfyUI_windows_portable\\python_embeded\\python.exe', 'custom_nodes/Lora-Training-in-Comfy/sd-scripts/train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=Z:\\Programmer\\ComfyUI_windows_portable\\ComfyUI\\models\\checkpoints\\SD_1.5\\Realistic\\v1-5-pruned.safetensors', '--train_data_dir=./ComfyUI/training/batch_test', '--output_dir=models/loras', '--logging_dir=./logs', '--log_prefix=Desired', 'name', 'for', 'LoRA.', '--resolution=512,512', '--network_module=networks.lora', '--max_train_epochs=16', '--learning_rate=1e-4', '--unet_lr=1.e-4', '--text_encoder_lr=1.e-4', '--lr_scheduler=cosine', '--lr_warmup_steps=0', '--lr_scheduler_num_cycles=1', '--network_dim=64', '--network_alpha=64', '--output_name=Desired', 'name', 'for', 'LoRA.', '--train_batch_size=8', '--save_every_n_epochs=8', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=2', '--cache_latents', '--prior_loss_weight=1', '--max_token_length=225', '--caption_extension=.txt', '--save_model_as=safetensors', '--min_bucket_reso=256', '--max_bucket_reso=1584', '--keep_tokens=1', '--xformers', '--shuffle_caption', '--clip_skip=2', '--optimizer_type=AdaFactor', '--min_snr_gamma=5.0', '--persistent_data_loader_workers', '--log_with=tensorboard']' returned non-zero exit status 2.
Train finished
Prompt executed in 7.14 seconds`

```

**Comment by readycade** [comment]
yeah, simple node works. that's disappointing about the advanced one though :( hopefully fixed soon.

**Comment by Indwoods** [comment]
> I actually found a fix if you go back to python 3.10.11 instead of 3.12.2 it will work

Is there Somewhere a clear and simple method to downgrade python version with pip cmd on embedded python, portable comfyui ?

**Comment by Battleshack** [comment]
**For those who has a working simple node but incompatible advanced node**  (and hasn't read through the whole readme):
You can edit the train.py file to configure your lora training.

**Comment by sapientsnap** [comment]
I've been working on this for two days. Third time reinstalling SD&CUI fresh, python3.10.16 (can't deprecate to 3.10.11) . I think I'm running cu121(not 100% sure, not sure how to verify).

Comfy working 100%, Captioning Node worked great, but can't get the Training Node to work at all. The node flashes green for a moment, but does nothing and does not produce an error in the UI. Running on a Mac M1. This is what I get in the MacOS Terminal... 

[]
/Users/kraniaqii/ComfyUI/custom_nodes/Lora-Training-in-Comfy/sd-scripts/train_network.py
/bin/sh: python: command not found
Train finished
Prompt executed in 0.04 seconds

It is calling ‘python’ but I believe it should be calling ‘python3’. I just don’t know where the call is being made from to change it as a troubleshooting step.

Any ideas?

**Comment by Battleshack** [comment]
> yeah, simple node works. that's disappointing about the advanced one though :( hopefully fixed soon.

If you have a working simple node, than the reason for advanced node not working is simply because of a typing error in the code. I've forked this repo and fixed the issue. Your welcome to use [my fork](https://github.com/Battleshack/Lora-Training-in-Comfy/tree/main), but I'll probably not keep it updated nor offer much support. I've also enabled bucked and changed some paramterers for the simple node.

**Comment by deepakgopan** [comment]
> Then try using python 3.10.11 and make sure you have everything properly installed and then do pip install -r then the text document

python 3.10.11 is the key
Yes exactly , also 

pip install wheel  torch==2.2.2 --index-url https://download.pytorch.org/whl/cu121 
numpy==1.26.4 
xformers==0.0.25.post1 

is the combo that will make this run and don't forget to upgrade pip using pip install --upgrade pip

Thank you so much @chase2598
