### ISSUE TITLE
Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by TwoPintOhh** [LarryJane491/Lora-Training-in-Comfy#56]
The pip insrall -f requirements_win.txt removes packages that are needed for ComfyUI to run and installs incompatable versions, breaking Comfy

to replicate this, install comfy, clone the git rep for Lora-Training-in-Comfy into the Custom nodes folder, pip install the requirements_win.txt

I have had the same issue using Stability matrix and the official ComfyUi installations, the following is via Stability Matrix after making sure Comfy was up to date. Comfy will not run.

```
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-06-25 07:51:07.673109
** Platform: Windows
** Python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
** Python executable: C:\Users\Pc\source\repos\SD\Data\Packages\ComfyUI\venv\Scripts\python.exe
** Log path: C:\Users\Pc\source\repos\SD\Data\Packages\ComfyUI\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: C:\Users\Pc\source\repos\SD\Data\Packages\ComfyUI\custom_nodes\rgthree-comfy
   1.6 seconds: C:\Users\Pc\source\repos\SD\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Manager

Traceback (most recent call last):
  File "C:\Users\Pc\source\repos\SD\Data\Packages\ComfyUI\main.py", line 76, in <module>
    import execution
  File "C:\Users\Pc\source\repos\SD\Data\Packages\ComfyUI\execution.py", line 11, in <module>
    import nodes
  File "C:\Users\Pc\source\repos\SD\Data\Packages\ComfyUI\nodes.py", line 21, in <module>
    import comfy.diffusers_load
  File "C:\Users\Pc\source\repos\SD\Data\Packages\ComfyUI\comfy\diffusers_load.py", line 3, in <module>
    import comfy.sd
  File "C:\Users\Pc\source\repos\SD\Data\Packages\ComfyUI\comfy\sd.py", line 5, in <module>
    from comfy import model_management
  File "C:\Users\Pc\source\repos\SD\Data\Packages\ComfyUI\comfy\model_management.py", line 119, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "C:\Users\Pc\source\repos\SD\Data\Packages\ComfyUI\comfy\model_management.py", line 88, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "C:\Users\Pc\source\repos\SD\Data\Packages\ComfyUI\venv\lib\site-packages\torch\cuda\__init__.py", line 778, in current_device
    _lazy_init()
  File "C:\Users\Pc\source\repos\SD\Data\Packages\ComfyUI\venv\lib\site-packages\torch\cuda\__init__.py", line 284, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```

**Comment by Fredrum** [comment]
I'm getting the same errors on twon new Comfy installs on windows+cuda.
Seems this toolset breaks Comfy?

**Comment by acgc99** [comment]
Same issue here, using or not Stability Matrix

**Comment by WilyGuys** [comment]
Any fix on this? Having the same problem... ComfyUI is broken

**Comment by TwoPintOhh** [comment]
I think these custom nodes are doing something weird. I just reinstalled comfy with stability matrix and not install this custom nodes.

**Comment by andimattes** [comment]
Check this: https://github.com/comfyanonymous/ComfyUI?tab=readme-ov-file#nvidia

As mentioned in the docs:
- `pip uninstall torch`
- `pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu124`
