### ISSUE TITLE
Library module not found

### ISSUE THREAD

**Issue by dcastleproject** [LarryJane491/Lora-Training-in-Comfy#57]
I reinstalled comfyui and the libs, after which I started receiving this issue on the node:

```bash
C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Lora-Training-in-Comfy/sd-scripts/train_network.py
The following values were not passed to `accelerate launch` and had defaults used instead:
        `--num_processes` was set to a value of `1`
        `--num_machines` was set to a value of `1`
        `--mixed_precision` was set to a value of `'no'`
        `--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Lora-Training-in-Comfy\sd-scripts\train_network.py", line 27, in <module>
    from library import model_util
ModuleNotFoundError: No module named 'library'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\accelerate\commands\launch.py", line 1107, in <module>
    main()
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\accelerate\commands\launch.py", line 1103, in main
    launch_command(args)
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\accelerate\commands\launch.py", line 1097, in launch_command
    simple_launcher(args)
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\accelerate\commands\launch.py", line 703, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\ComfyUI_windows_portable\\python_embeded\\python.exe', 'C:/ComfyUI_windows_portable/ComfyUI/custom_nodes/Lora-Training-in-Comfy/sd-scripts/train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=C:\\ComfyUI_windows_portable\\ComfyUI\\models\\checkpoints\\Juggernaut_X_RunDiffusion.safetensors', '--train_data_dir=C:/ComfyUI_windows_portable/ComfyUI/input/train', '--output_dir=models/loras', '--logging_dir=./logs', '--log_prefix=Dociinho', '--resolution=512,512', '--network_module=networks.lora', '--max_train_epochs=20', '--learning_rate=1e-4', '--unet_lr=1e-4', '--text_encoder_lr=1e-5', '--lr_scheduler=cosine_with_restarts', '--lr_warmup_steps=0', '--lr_scheduler_num_cycles=1', '--network_dim=32', '--network_alpha=32', '--output_name=Dociinho', '--train_batch_size=1', '--save_every_n_epochs=20', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=26', '--cache_latents', '--prior_loss_weight=1', '--max_token_length=225', '--caption_extension=.txt', '--save_model_as=safetensors', '--min_bucket_reso=256', '--max_bucket_reso=1584', '--keep_tokens=0', '--xformers', '--shuffle_caption', '--clip_skip=2', '--optimizer_type=AdamW8bit', '--persistent_data_loader_workers', '--log_with=tensorboard', '--clip_skip=2', '--optimizer_type=AdamW8bit', '--persistent_data_loader_workers', '--log_with=tensorboard']' returned non-zero exit status 1.
Train finished
Prompt executed in 8.71 seconds```

**Comment by Snoopy3333** [comment]
Hi there,

After I corrected the "path" issue by starting ComfyUi not from "ComfyUI_windows_portable" but from "ComfyUI_windows_portable\ComfyUI\" I've got the same problem here:

` File "G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Lora-Training-in-Comfy\sd-scripts\train_network.py", line 27, in <module>
    from library import model_util
ModuleNotFoundError: No module named 'library'`

Is anybody able to help?

**Comment by JeremyGuo** [comment]
https://github.com/LarryJane491/Lora-Training-in-Comfy/pull/52
