### ISSUE TITLE
ModuleNotFoundError: No module name 'library'

### ISSUE THREAD

**Issue by Snoopy3333** [LarryJane491/Lora-Training-in-Comfy#60]
Hi there,
I'm having trouble running the training. I always get the error mentioned above.

Steps already taken:

1)
Tested if "library" is available (pip list) ===> 'library was not shown'

2)
Tried to install it: pip install library ====> Now 'pip list' lists a module 'Library'   (L in capital letters ??)

3) searched for *library*, found:
library.py in "G:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch"
library.h in "G:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\include\torch"

Now I'm out of any idea. Somebody out there who can help?
Thanks in advance,
Michael

Here's the output:

`Traceback (most recent call last):
  File "G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Lora-Training-in-Comfy\sd-scripts\train_network.py", line 27, in <module>
    from library import model_util
ModuleNotFoundError: No module named 'library'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "G:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\accelerate\commands\launch.py", line 1107, in <module>
    main()
  File "G:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\accelerate\commands\launch.py", line 1103, in main
    launch_command(args)
  File "G:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\accelerate\commands\launch.py", line 1097, in launch_command
    simple_launcher(args)
  File "G:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\accelerate\commands\launch.py", line 703, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['G:\\ComfyUI_windows_portable\\python_embeded\\python.exe', 'custom_nodes/Lora-Training-in-Comfy/sd-scripts/train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=G:\\ComfyUI_windows_portable\\ComfyUI\\models\\checkpoints\\ponyRealism_v20VAE.safetensors', '--train_data_dir=G:/ComfyUI_Database', '--output_dir=models/loras', '--logging_dir=./logs', '--log_prefix=TestLoraTrain', '--resolution=1024,1024', '--network_module=networks.lora', '--max_train_epochs=400', '--learning_rate=1e-4', '--unet_lr=1.e-4', '--text_encoder_lr=1.e-4', '--lr_scheduler=cosine_with_restarts', '--lr_warmup_steps=0', '--lr_scheduler_num_cycles=1', '--network_dim=32', '--network_alpha=32', '--output_name=TestLoraTrain', '--train_batch_size=1', '--save_every_n_epochs=50', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=18', '--cache_latents', '--prior_loss_weight=1', '--max_token_length=225', '--caption_extension=.txt', '--save_model_as=safetensors', '--min_bucket_reso=256', '--max_bucket_reso=1584', '--keep_tokens=0', '--xformers', '--shuffle_caption', '--clip_skip=2', '--optimizer_type=AdamW8bit', '--persistent_data_loader_workers', '--log_with=tensorboard']' returned non-zero exit status 1.
Train finished
Prompt executed in 3.46 seconds`

**Comment by JeremyGuo** [comment]
https://github.com/LarryJane491/Lora-Training-in-Comfy/pull/52

see my pull request which solved this issue.
