### ISSUE TITLE
[WinError 126]

### ISSUE THREAD

**Issue by leehexng** [LarryJane491/Lora-Training-in-Comfy#64]
got prompt
[]
D:\ComfyUI Files\ComfyUI_Clean Ver\ComfyUI\custom_nodes\Lora-Training-in-Comfy/sd-scripts/train_network.py
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 112, in _get_module_details
  File "C:\Users\INT010\AppData\Local\Programs\Python\Python311\Lib\site-packages\accelerate\__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "C:\Users\INT010\AppData\Local\Programs\Python\Python311\Lib\site-packages\accelerate\accelerator.py", line 33, in <module>
    import torch
  File "C:\Users\INT010\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\__init__.py", line 148, in <module>
    raise err
OSError: [WinError 126] 지정된 모듈을 찾을 수 없습니다. Error loading "C:\Users\INT010\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.
Train finished
Prompt executed in 9.62 seconds

I got this issues while training my Lora in ComfyUI. Is there anyone know how to fix this ?

**Comment by makekake** [comment]
I have this same error

**Comment by FlyingPTT** [comment]
me too
