### ISSUE TITLE
my comfy was running just fine then i insatlled lora training. and closed down comfy for the night. now i cant get back in!

### ISSUE THREAD

**Issue by rachelcenter** [LarryJane491/Lora-Training-in-Comfy#69]
my comfy was running just fine then i installed lora training (through manager). and closed down comfy for the night. now i cant get back in! https://github.com/comfyanonymous/ComfyUI/issues/4608 

D:\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-08-25 21:59:24.244525
** Platform: Windows
** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
** Python executable: D:\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: D:\ComfyUI_windows_portable\ComfyUI
** Log path: D:\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use
   2.1 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\main.py", line 86, in <module>
    import execution
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 13, in <module>
    import nodes
  File "D:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 21, in <module>
    import comfy.diffusers_load
  File "D:\ComfyUI_windows_portable\ComfyUI\comfy\diffusers_load.py", line 3, in <module>
    import comfy.sd
  File "D:\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 5, in <module>
    from comfy import model_management
  File "D:\ComfyUI_windows_portable\ComfyUI\comfy\model_management.py", line 142, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
                                  ^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\comfy\model_management.py", line 111, in get_torch_device
    return torch.device(torch.cuda.current_device())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\cuda\__init__.py", line 878, in current_device
    _lazy_init()
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\cuda\__init__.py", line 305, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

D:\ComfyUI_windows_portable>pause
Press any key to continue . . .

**Comment by seon-geun** [comment]
Same issue, got my ComfyUI back up running by removing the ComfyUI/custom_nodes/Lora-Training-in-Comfy folder and running update/update_comfyui_and_python_dependencies.bat
Couldn't get this repo to run though.

**Comment by rachelcenter** [comment]
> Same issue, got my ComfyUI back up running by removing the ComfyUI/custom_nodes/Lora-Training-in-Comfy folder and running update/update_comfyui_and_python_dependencies.bat Couldn't get this repo to run though.

i tried that and didnt work for me, i had to reinstall from scratch. Hope the author will fix this "training" node that people can download from manager, or remove it from manager. what a nightmare

**Comment by ninchistudios** [comment]
Same issue. Installed from Manager, restarted server, "AssertionError: Torch not compiled with CUDA enabled". CPU mode works  to uninstall this.

**Comment by LongToeBoy** [comment]
> Same issue. Installed from Manager, restarted server, "AssertionError: Torch not compiled with CUDA enabled". CPU mode works to uninstall this.

if torch was not compiled with CUDA enabled, it probably didn't see CUDA toolkit installed. are you sure it's in path? did you install CUDA toolkit at all? if yes, you'll have to `python -m pip uninstall xformers, bitsandbytes, torch, torchvision -y` and then `python -m pip install xformers, bitsandbytes, torchvision`. have been exactly there
