### ISSUE TITLE
Training Issue

### ISSUE THREAD

**Issue by chnisar515** [LarryJane491/Lora-Training-in-Comfy#71]
I have installed the (Lora-Traning_in_Comjy) custom node. and i am using Portable Comfyui in windows 11 and i have RTX3060. My comfy is fully updated. I also installed the requirment.txt and now when i try to train lora it getting prompt but after few seconds it show its completed but when i check in folder Lora there is no Lora show. below is the log of after i press queue Prompt

got prompt
[]
C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Lora-Training-in-Comfy/sd-scripts/train_network.py
The following values were not passed to `accelerate launch` and had defaults used instead:
        `--num_processes` was set to a value of `0`
        `--num_machines` was set to a value of `1`
        `--mixed_precision` was set to a value of `'no'`
        `--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Lora-Training-in-Comfy\sd-scripts\train_network.py", line 26, in <module>
    from diffusers import DDPMScheduler
  File "C:\roop-unleashed-main\installer\installer_files\env\lib\site-packages\diffusers\__init__.py", line 4, in <module>
    from .utils import is_inflect_available, is_transformers_available, is_unidecode_available
  File "C:\roop-unleashed-main\installer\installer_files\env\lib\site-packages\diffusers\utils\__init__.py", line 18, in <module>
    import importlib_metadata
ModuleNotFoundError: No module named 'importlib_metadata'
Traceback (most recent call last):
  File "C:\roop-unleashed-main\installer\installer_files\env\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\roop-unleashed-main\installer\installer_files\env\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\roop-unleashed-main\installer\installer_files\env\lib\site-packages\accelerate\commands\launch.py", line 996, in <module>
    main()
  File "C:\roop-unleashed-main\installer\installer_files\env\lib\site-packages\accelerate\commands\launch.py", line 992, in main
    launch_command(args)
  File "C:\roop-unleashed-main\installer\installer_files\env\lib\site-packages\accelerate\commands\launch.py", line 986, in launch_command
    simple_launcher(args)
  File "C:\roop-unleashed-main\installer\installer_files\env\lib\site-packages\accelerate\commands\launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\roop-unleashed-main\\installer\\installer_files\\env\\python.exe', 'C:/ComfyUI_windows_portable/ComfyUI/custom_nodes/Lora-Training-in-Comfy/sd-scripts/train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=C:\\ComfyUI_windows_portable\\ComfyUI\\models\\checkpoints\\realisticStockPhoto_v30SD15.safetensors', '--train_data_dir=C:/1_nini', '--output_dir=models/loras', '--logging_dir=./logs', '--log_prefix=Nini_Lora_jibMixRealisticXL', '--resolution=512,512', '--network_module=networks.lora', '--max_train_epochs=10', '--learning_rate=1e-4', '--unet_lr=1e-4', '--text_encoder_lr=1e-5', '--lr_scheduler=cosine_with_restarts', '--lr_warmup_steps=0', '--lr_scheduler_num_cycles=1', '--network_dim=32', '--network_alpha=32', '--output_name=Nini_Lora_jibMixRealisticXL', '--train_batch_size=1', '--save_every_n_epochs=10', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=28', '--cache_latents', '--prior_loss_weight=1', '--max_token_length=225', '--caption_extension=.txt', '--save_model_as=safetensors', '--min_bucket_reso=256', '--max_bucket_reso=1584', '--keep_tokens=0', '--xformers', '--shuffle_caption', '--v2', '--optimizer_type=AdamW8bit', '--persistent_data_loader_workers', '--log_with=tensorboard', '--clip_skip=2', '--optimizer_type=AdamW8bit', '--persistent_data_loader_workers', '--log_with=tensorboard', '--clip_skip=2', '--optimizer_type=AdamW8bit', '--persistent_data_loader_workers', '--log_with=tensorboard', '--clip_skip=2', '--optimizer_type=AdamW8bit', '--persistent_data_loader_workers', '--log_with=tensorboard', '--clip_skip=2', '--optimizer_type=AdamW8bit', '--persistent_data_loader_workers', '--log_with=tensorboard']' returned non-zero exit status 1.
Train finished
Prompt executed in 6.07 seconds

**Comment by chnisar515** [comment]
C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Lora-Training-in-Comfy/sd-scripts/train_network.py
The following values were not passed to `accelerate launch` and had defaults used instead:
        `--num_processes` was set to a value of `1`
        `--num_machines` was set to a value of `1`
        `--mixed_precision` was set to a value of `'no'`
        `--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Lora-Training-in-Comfy\sd-scripts\train_network.py", line 26, in <module>
    from diffusers import DDPMScheduler
  File "C:\roop-unleashed-main\installer\installer_files\env\lib\site-packages\diffusers\__init__.py", line 4, in <module>
    from .utils import is_inflect_available, is_transformers_available, is_unidecode_available
  File "C:\roop-unleashed-main\installer\installer_files\env\lib\site-packages\diffusers\utils\__init__.py", line 18, in <module>
    import importlib_metadata
ModuleNotFoundError: No module named 'importlib_metadata'
Traceback (most recent call last):
  File "C:\roop-unleashed-main\installer\installer_files\env\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\roop-unleashed-main\installer\installer_files\env\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\roop-unleashed-main\installer\installer_files\env\lib\site-packages\accelerate\commands\launch.py", line 996, in <module>
    main()
  File "C:\roop-unleashed-main\installer\installer_files\env\lib\site-packages\accelerate\commands\launch.py", line 992, in main
    launch_command(args)
  File "C:\roop-unleashed-main\installer\installer_files\env\lib\site-packages\accelerate\commands\launch.py", line 986, in launch_command
    simple_launcher(args)
  File "C:\roop-unleashed-main\installer\installer_files\env\lib\site-packages\accelerate\commands\launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\roop-unleashed-main\\installer\\installer_files\\env\\python.exe', 'C:/ComfyUI_windows_portable/ComfyUI/custom_nodes/Lora-Training-in-Comfy/sd-scripts/train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=C:\\ComfyUI_windows_portable\\ComfyUI\\models\\checkpoints\\epicrealism_naturalSinRC1VAE.safetensors', '--train_data_dir=C:/database', '--output_dir=models/loras', '--logging_dir=./logs', '--log_prefix=Nini_Lora_jibMixRealisticXL', '--resolution=512,512', '--network_module=networks.lora', '--max_train_epochs=50', '--learning_rate=1e-4', '--unet_lr=1e-4', '--text_encoder_lr=1e-5', '--lr_scheduler=cosine_with_restarts', '--lr_warmup_steps=0', '--lr_scheduler_num_cycles=1', '--network_dim=32', '--network_alpha=32', '--output_name=Nini_Lora_jibMixRealisticXL', '--train_batch_size=1', '--save_every_n_epochs=10', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=14', '--cache_latents', '--prior_loss_weight=1', '--max_token_length=225', '--caption_extension=.txt', '--save_model_as=safetensors', '--min_bucket_reso=256', '--max_bucket_reso=1584', '--keep_tokens=0', '--xformers', '--shuffle_caption', '--clip_skip=2', '--optimizer_type=AdamW8bit', '--persistent_data_loader_workers', '--log_with=tensorboard', '--clip_skip=2', '--optimizer_type=AdamW8bit', '--persistent_data_loader_workers', '--log_with=tensorboard', '--clip_skip=2', '--optimizer_type=AdamW8bit', '--persistent_data_loader_workers', '--log_with=tensorboard', '--clip_skip=2', '--optimizer_type=AdamW8bit', '--persistent_data_loader_workers', '--log_with=tensorboard']' returned non-zero exit status 1.
Train finished
Prompt executed in 5.82 seconds

**Comment by veeroo18** [comment]
I am facing similar issues with various modules .. there must be some error regarding python path and modules connection
