### ISSUE TITLE
Training stop after loading the dataset

### ISSUE THREAD

**Issue by Tonhiox** [LarryJane491/Lora-Training-in-Comfy#78]
Hey guys ! 

I've been struggling with the Lora Training for the last 3 days. It was working well on my computer last week. 

I reinstall torch, torchvision, started from a new ComfyUI with no other custom nodes, reinstall Cuda, downgrade to Python 3.10.11...

I'm going round in circles, and I'm out of ideas now...

Here the message from cmd prompt is giving me :

```
C:\Users\Artist\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\Lora-Training-in-Comfy/sd-scripts/train_network.py
The following values were not passed to `accelerate launch` and had defaults used instead:
        `--num_processes` was set to a value of `0`
        `--num_machines` was set to a value of `1`
        `--mixed_precision` was set to a value of `'no'`
        `--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
prepare tokenizer
update token length: 225
Using DreamBooth method.
prepare images.
found directory K:\21_rnd_IA\00_IN\00_influencer_data\cristyren\photoDatabase\5_cristyren contains 278 image files
1390 train images with repeating.
0 reg images.
no regularization images / 正則化画像が見つかりませんでした
[Dataset 0]
  batch_size: 1
  resolution: (512, 512)
  enable_bucket: True
  min_bucket_reso: 256
  max_bucket_reso: 1584
  bucket_reso_steps: 64
  bucket_no_upscale: False

  [Subset 0 of Dataset 0]
    image_dir: "K:\21_rnd_IA\00_IN\00_influencer_data\cristyren\photoDatabase\5_cristyren"
    image_count: 278
    num_repeats: 5
    shuffle_caption: True
    keep_tokens: 0
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    caption_prefix: None
    caption_suffix: None
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: cristyren
    caption_extension: .txt


[Dataset 0]
loading image sizes.
100%|███████████████████████████████████████████████████████████████████████████████| 278/278 [00:00<00:00, 289.19it/s]
make buckets
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (384, 640), count: 165
bucket 1: resolution (448, 576), count: 1220
bucket 2: resolution (512, 512), count: 5
mean ar error (without repeats): 0.02812264765125123
preparing accelerator
C:\Users\Artist\.pyenv\pyenv-win\versions\3.10.11\lib\site-packages\accelerate\accelerator.py:443: UserWarning: `log_with=tensorboard` was passed but no supported trackers are currently installed.
  warnings.warn(f"`log_with={log_with}` was passed but no supported trackers are currently installed.")
loading model for process 0/1
load StableDiffusion checkpoint: C:\Users\Artist\Documents\ComfyUI_windows_portable\ComfyUI\models\checkpoints\realisticVisionV60B1_v51HyperVAE.safetensors
UNet2DConditionModel: 64, 8, 768, False, False
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
Traceback (most recent call last):
  File "C:\Users\Artist\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\Lora-Training-in-Comfy\sd-scripts\train_network.py", line 1012, in <module>
    trainer.train(args)
  File "C:\Users\Artist\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\Lora-Training-in-Comfy\sd-scripts\train_network.py", line 228, in train
    model_version, text_encoder, vae, unet = self.load_target_model(args, weight_dtype, accelerator)
  File "C:\Users\Artist\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\Lora-Training-in-Comfy\sd-scripts\train_network.py", line 102, in load_target_model
    text_encoder, vae, unet, _ = train_util.load_target_model(args, weight_dtype, accelerator)
  File "C:\Users\Artist\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\Lora-Training-in-Comfy\sd-scripts\library\train_util.py", line 3917, in load_target_model
    text_encoder, vae, unet, load_stable_diffusion_format = _load_target_model(
  File "C:\Users\Artist\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\Lora-Training-in-Comfy\sd-scripts\library\train_util.py", line 3860, in _load_target_model
    text_encoder, vae, unet = model_util.load_models_from_stable_diffusion_checkpoint(
  File "C:\Users\Artist\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\Lora-Training-in-Comfy\sd-scripts\library\model_util.py", line 1072, in load_models_from_stable_diffusion_checkpoint
    info = text_model.load_state_dict(converted_text_encoder_checkpoint)
  File "C:\Users\Artist\.pyenv\pyenv-win\versions\3.10.11\lib\site-packages\torch\nn\modules\module.py", line 2215, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CLIPTextModel:
        Unexpected key(s) in state_dict: "text_model.embeddings.position_ids".
Traceback (most recent call last):
  File "C:\Users\Artist\.pyenv\pyenv-win\versions\3.10.11\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Artist\.pyenv\pyenv-win\versions\3.10.11\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Artist\.pyenv\pyenv-win\versions\3.10.11\lib\site-packages\accelerate\commands\launch.py", line 1178, in <module>
    main()
  File "C:\Users\Artist\.pyenv\pyenv-win\versions\3.10.11\lib\site-packages\accelerate\commands\launch.py", line 1174, in main
    launch_command(args)
  File "C:\Users\Artist\.pyenv\pyenv-win\versions\3.10.11\lib\site-packages\accelerate\commands\launch.py", line 1168, in launch_command
    simple_launcher(args)
  File "C:\Users\Artist\.pyenv\pyenv-win\versions\3.10.11\lib\site-packages\accelerate\commands\launch.py", line 763, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\Artist\\.pyenv\\pyenv-win\\versions\\3.10.11\\python.exe', 'C:/Users/Artist/Documents/ComfyUI_windows_portable/ComfyUI/custom_nodes/Lora-Training-in-Comfy/sd-scripts/train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=C:\\Users\\Artist\\Documents\\ComfyUI_windows_portable\\ComfyUI\\models\\checkpoints\\realisticVisionV60B1_v51HyperVAE.safetensors', '--train_data_dir=K:/21_rnd_IA/00_IN/00_influencer_data/cristyren/photoDatabase', '--output_dir=models/loras', '--logging_dir=./logs', '--log_prefix=cristyren_RV6', '--resolution=512,512', '--network_module=networks.lora', '--max_train_epochs=3', '--learning_rate=1e-4', '--unet_lr=1e-4', '--text_encoder_lr=1e-5', '--lr_scheduler=cosine_with_restarts', '--lr_warmup_steps=0', '--lr_scheduler_num_cycles=1', '--network_dim=32', '--network_alpha=32', '--output_name=cristyren_RV6', '--train_batch_size=1', '--save_every_n_epochs=10', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=19', '--cache_latents', '--prior_loss_weight=1', '--max_token_length=225', '--caption_extension=.txt', '--save_model_as=safetensors', '--min_bucket_reso=256', '--max_bucket_reso=1584', '--keep_tokens=0', '--xformers', '--shuffle_caption', '--clip_skip=2', '--optimizer_type=AdamW8bit', '--persistent_data_loader_workers', '--log_with=tensorboard']' returned non-zero exit status 1.
Train finished
Prompt executed in 16.90 seconds
```

Thanks for your help

**Comment by Frontesque** [comment]
I'm experiencing the same issue with an 11 image dataset on Linux with python 3.12.

edit: We appear to be using the same SD model, realisticvision, but switching to something smaller still gives the error.

**Comment by emosGambler** [comment]
Find `model_util.py` file in `../custom_nodes/`, then open the file with any editor. Then find line:
`# support checkpoint without position_ids (invalid checkpoint)`
and instead of:
`# support checkpoint without position_ids (invalid checkpoint)
if "text_model.embeddings.position_ids" not in text_model_dict:
    text_model_dict["text_model.embeddings.position_ids"] = torch.arange(77).unsqueeze(0)  # 77 is the max length of the text`
have there:
`# remove position_ids for newer transformer, which causes error :(
if "text_model.embeddings.position_ids" in text_model_dict:
    text_model_dict.pop("text_model.embeddings.position_ids")`

Based on: https://github.com/open-mmlab/PIA/issues/13#issuecomment-2577458281
