### ISSUE TITLE
these are the errors i get on amd with rocm

### ISSUE THREAD

**Issue by azamet90** [LarryJane491/Lora-Training-in-Comfy#82]
*** Checking and updating to new version if possible
Already up to date.

#######################################################################
[ComfyUI-Manager] Starting dependency installation/(de)activation for the extension

[ComfyUI-Manager] skip black listed pip installation: 'transformers'

## Execute install/(de)activation script for 'D:\yapay zeka\ComfyUI-Zluda\custom_nodes\Lora-Training-in-Comfy'
 Collecting xformers
   Using cached xformers-0.0.28.post3.tar.gz (7.8 MB)
   Preparing metadata (setup.py): started
   Preparing metadata (setup.py): finished with status 'error'
[!]   error: subprocess-exited-with-error
[!]
[!]   python setup.py egg_info did not run successfully.
[!]   exit code: 1
[!]
[!]   [12 lines of output]
[!]   No ROCm runtime is found, using ROCM_HOME='C:\Program Files\AMD\ROCm\5.7'
[!]   Traceback (most recent call last):
[!]     File "<string>", line 2, in <module>
[!]     File "<pip-setuptools-caller>", line 34, in <module>
[!]     File "C:\Users\CilginFlix\AppData\Local\Temp\pip-install-xejw6r28\xformers_121f72e31f98428bbd2c4ebfbacc40b4\setup.py", line 25, in <module>
[!]       from torch.utils.cpp_extension import (
[!]     File "D:\yapay zeka\ComfyUI-Zluda\venv\Lib\site-packages\torch\utils\cpp_extension.py", line 204, in <module>
[!]       HIP_HOME = _join_rocm_home('hip') if ROCM_HOME else None
[!]                  ^^^^^^^^^^^^^^^^^^^^^^
[!]     File "D:\yapay zeka\ComfyUI-Zluda\venv\Lib\site-packages\torch\utils\cpp_extension.py", line 157, in _join_rocm_home
[!]       raise OSError('Building PyTorch extensions using '
[!]   OSError: Building PyTorch extensions using ROCm and Windows is not supported.
[!]   [end of output]
[!]
[!]   note: This error originates from a subprocess, and is likely not a problem with pip.
[!] error: metadata-generation-failed
[!]
[!] Encountered error while generating package metadata.
[!]
[!] See above for output.
[!]
[!] note: This is an issue with the package mentioned above, not pip.
[!] hint: See above for details.
install/(de)activation script failed: D:\yapay zeka\ComfyUI-Zluda\custom_nodes\Lora-Training-in-Comfy

**Comment by CompliantCompiler-CC** [comment]
Don't install it, It installs nvidia and cuda, which is so unwanted for AMDGPU users. But why AMDGPU on Windows? It's cursed literally. It would be better on linux. It doesn't have any AMD support at all, and installs that nvidia contamination.

**Comment by CompliantCompiler-CC** [comment]
I think you should install ComfyUI from scratch again, it got heavily damaged by this thing called.. NVIDIA and CUDA deps.
